package code.view;

public class Lua_chon extends javax.swing.JFrame {

    public Lua_chon() {
        initComponents();
        setTitle("TVQK&NDN SHOE SHOP - Thoải mái trong từng bước chân!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_quanly = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        ban_hang = new javax.swing.JButton();
        nhap_hang = new javax.swing.JButton();
        thong_ke = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thoải mái trong từng bước chân!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        btn_quanly.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btn_quanly.setForeground(new java.awt.Color(0, 0, 102));
        btn_quanly.setText("TVQK&NDN SHOE SHOP");
        btn_quanly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quanly, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 620, 110));

        btn_Thoat.setBackground(new java.awt.Color(0, 0, 102));
        btn_Thoat.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 750, 108, -1));

        ban_hang.setBackground(new java.awt.Color(0, 204, 51));
        ban_hang.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        ban_hang.setForeground(new java.awt.Color(255, 255, 255));
        ban_hang.setText("Bán hàng");
        ban_hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban_hangActionPerformed(evt);
            }
        });
        jPanel1.add(ban_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 340, 220));

        nhap_hang.setBackground(new java.awt.Color(0, 204, 51));
        nhap_hang.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        nhap_hang.setForeground(new java.awt.Color(255, 255, 255));
        nhap_hang.setText("Nhập hàng");
        nhap_hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhap_hangActionPerformed(evt);
            }
        });
        jPanel1.add(nhap_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 340, 220));
        
        thong_ke.setBackground(new java.awt.Color(0, 204, 51));
        thong_ke.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        thong_ke.setForeground(new java.awt.Color(255, 255, 255));
        thong_ke.setText("Thống kê");
        thong_ke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thong_keActionPerformed(evt);
            }
        });
        jPanel1.add(thong_ke, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 340, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1150, 790));

        pack();
    }// </editor-fold>                        

    public void Nhap_hang_vao() {
        Nhap_hang nh = new Nhap_hang();
        Lua_chon lc = new Lua_chon();

        lc.setVisible(false);
        nh.setVisible(true);
        dispose();
    }

    public void Ban_hang_ra() {
        Ban_hang nh = new Ban_hang();
        Lua_chon lc = new Lua_chon();

        lc.setVisible(false);
        nh.setVisible(true);
        dispose();
    }
    
    public void Thong_ke_dt() {
        Thong_ke nh = new Thong_ke();
        Lua_chon lc = new Lua_chon();

        lc.setVisible(false);
        nh.setVisible(true);
        dispose();
    }

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }

    private void btn_quanlyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void ban_hangActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Ban_hang_ra();
    }

    private void nhap_hangActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Nhap_hang_vao();
    }
    
    private void thong_keActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Thong_ke_dt();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ban_hang;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_quanly;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nhap_hang;
    private javax.swing.JButton thong_ke;
    // End of variables declaration                   
}
