// ĐIỀU KHIỂN GIAO DIỆN NHẬP HÀNG
package code.view; 

import code.control.BanhangHandler;
import code.dao.LoaiSPDAO;
import code.lop.LoaiSp;
import code.lop.SanPham;
import code.dao.SanPhamDAO;
import java.io.*;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.logging.*;
import javax.swing.table.TableRowSorter;
import javax.xml.parsers.*;
import org.xml.sax.SAXException;

public class Thong_ke extends javax.swing.JFrame {

    LoaiSPDAO daoLoaiSP = new LoaiSPDAO();
    SanPhamDAO daoSP = new SanPhamDAO();
    DefaultTableModel SpdabanModel;

    public Thong_ke() {
        initComponents();
        setLocationRelativeTo(null);
        getDataCombobox();
        setTitle("TVQK&NDN SHOE SHOP - Thoải mái trong từng bước chân!");

        // Sắp xếp sản phẩm trong bảng kho hàng
        SpdabanModel = (DefaultTableModel) tbl_spdaban.getModel();
        TableRowSorter<DefaultTableModel> sorter1 = new TableRowSorter<>(SpdabanModel);
        SpdabanModel.setRowCount(0);
        tbl_spdaban.setRowSorter(sorter1);
        sorter1.setComparator(0, new Comparator<String>() {
            @Override
            public int compare(String s1, String s2) {
                return s1.compareTo(s2);
            }
        });
        sorter1.setSortable(0, true);
        sorter1.toggleSortOrder(0);
        ImportBanhang();
        
        try {
            setNgay();
            
        } catch (ParseException ex) {
            Logger.getLogger(Thong_ke.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void setNgay() throws ParseException {
        DateFormat dateFormat = new SimpleDateFormat("E MMM dd HH:mm:ss zzz yyyy");
        Date date = dateFormat.parse("Mon Jan 01 19:07:24 ICT 2024");
        txt_Ngay1.setDate(date);
        resetForm();
    }

    // Lấy dữ liệu từ combobox
    public void getDataCombobox() {
        @SuppressWarnings("unchecked")
        DefaultComboBoxModel<LoaiSp> model = (DefaultComboBoxModel) cboLoaiSp.getModel();
        model.addElement(new LoaiSp("0", "- Lựa Chọn -"));
        for (LoaiSp loai : daoLoaiSP.getAllLoaiSp()) {
            model.addElement(loai);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_quanly = new javax.swing.JButton();
        lbl_logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_spdaban = new javax.swing.JTable();
        btn_quaylai = new javax.swing.JButton();
        btn_Thoat1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tongsp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tongtien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Lai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ThongKe = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_MaSp = new javax.swing.JTextField();
        txt_Ngay1 = new com.toedter.calendar.JDateChooser();
        txt_Ngay2 = new com.toedter.calendar.JDateChooser();
        cboLoaiSp = new javax.swing.JComboBox<>();
        Lam_moi = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_quanly.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        btn_quanly.setForeground(new java.awt.Color(0, 0, 102));
        btn_quanly.setText("TVQK&NDN SHOE SHOP");
        btn_quanly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quanly, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 34, 570, 50));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/logo_shop.png"))); // NOI18N
        lbl_logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_logo.setMaximumSize(new java.awt.Dimension(1014, 572));
        lbl_logo.setMinimumSize(new java.awt.Dimension(1014, 572));
        jPanel1.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, 296));

        tbl_spdaban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Ngày bán", "Loại sản phẩm", "Số lượng ", "Giá bán (VNĐ/đôi)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_spdaban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_spdabanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_spdaban);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 680, 230));

        btn_quaylai.setBackground(new java.awt.Color(0, 0, 102));
        btn_quaylai.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_quaylai.setForeground(new java.awt.Color(255, 255, 255));
        btn_quaylai.setText("Quay lại");
        btn_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaylaiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quaylai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 750, 108, -1));

        btn_Thoat1.setBackground(new java.awt.Color(0, 0, 102));
        btn_Thoat1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_Thoat1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat1.setText("Thoát");
        btn_Thoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Thoat1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Thoat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 750, 108, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH SẢN PHẨM ĐÃ BÁN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 310, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Tổng số sản phẩm đã bán: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));
        jPanel1.add(Tongsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Tổng doanh thu: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 130, -1));
        jPanel1.add(Tongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 220, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Lợi nhuận:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, -1, -1));
        jPanel1.add(Lai, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 220, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setText("THỐNG KÊ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        ThongKe.setText("Thống kê");
        ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeActionPerformed(evt);
            }
        });
        jPanel1.add(ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 100, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setText("Loại sản phẩm:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setText("Đến ngày:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel8.setText("Mã sản phẩm:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));
        jPanel1.add(txt_MaSp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 220, -1));
        jPanel1.add(txt_Ngay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 220, -1));
        jPanel1.add(txt_Ngay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 220, -1));

        jPanel1.add(cboLoaiSp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 220, -1));

        Lam_moi.setText("Làm mới");
        Lam_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lam_moiActionPerformed(evt);
            }
        });
        jPanel1.add(Lam_moi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 100, 80));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel10.setText("Từ ngày:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void resetForm() throws ParseException {
        Date today = new Date();
        txt_MaSp.setText("");
        DateFormat dateFormat = new SimpleDateFormat("E MMM dd HH:mm:ss zzz yyyy");
        Date date = dateFormat.parse("Mon Jan 01 19:07:24 ICT 2024");
        txt_Ngay1.setDate(date);
        txt_Ngay2.setDate(today);
        cboLoaiSp.setSelectedIndex(0);
        Tongsp.setText("");
        Tongtien.setText("");
        Lai.setText("");
    }

    // Lấy dữ liệu từ file sanpham.xml
    public void ImportBanhang() {
        FileInputStream fis = null;
        try {
            fis = new FileInputStream("banhang.xml");
            SAXParserFactory factory = SAXParserFactory.newInstance();
            SAXParser parser = factory.newSAXParser();

            BanhangHandler handler = new BanhangHandler();

            parser.parse(fis, handler);

            daoSP.sanphamlist = handler.getBanhanglist();

            SpdabanModel.setRowCount(0);

            for (SanPham sp : daoSP.sanphamlist) {
                DecimalFormat decimalFormat = new DecimalFormat("#,###");
                String format = decimalFormat.format(sp.getGiaban());
                String format1 = decimalFormat.format(sp.getSoluongban());
                SpdabanModel.addRow(new Object[]{
                    sp.getMaSp(), sp.getTenSp(),
                    sp.getNgayban(), sp.getLoaisp(),
                    format1, format
                });
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Nhap_hang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Nhap_hang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Nhap_hang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Nhap_hang.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fis.close();
            } catch (IOException ex) {
                Logger.getLogger(Nhap_hang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void quay_lai() {
        Nhap_hang nh = new Nhap_hang();
        Lua_chon lc = new Lua_chon();

        lc.setVisible(true);
        nh.setVisible(false);
        dispose();
    }

    private void btn_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaylaiActionPerformed
        // TODO add your handling code here:
        quay_lai();
    }//GEN-LAST:event_btn_quaylaiActionPerformed

    private void tbl_spdabanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_spdabanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_spdabanMouseClicked

    private void btn_quanlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlyActionPerformed
        try {
            // TODO add your handling code here:
            resetForm();
        } catch (ParseException ex) {
            Logger.getLogger(Thong_ke.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_quanlyActionPerformed

    private void btn_Thoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Thoat1ActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btn_Thoat1ActionPerformed

    private void Lam_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lam_moiActionPerformed
        try {
            // TODO add your handling code here:
            resetForm();
        } catch (ParseException ex) {
            Logger.getLogger(Thong_ke.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Lam_moiActionPerformed

    private void ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeActionPerformed
        // TODO add your handling code here:
        
        if (txt_MaSp.getText().isEmpty() && cboLoaiSp.getSelectedItem().toString().equalsIgnoreCase("- Lựa Chọn -")) {
            int tsp=0;
            long dt=0;
            long ln=0;
            Date date1 = txt_Ngay1.getDate();
            Date date2 = txt_Ngay2.getDate();
            for (SanPham sp : daoSP.sanphamlist) {
                try {
                    DateFormat dateFormat = new SimpleDateFormat("E MMM dd HH:mm:ss zzz yyyy");
                    Date date = dateFormat.parse(sp.getNgayban());
                    if (date.compareTo(date1)>0 && date.compareTo(date2)<0 ) {
                        tsp += sp.getSoluongban();
                        dt += (long) sp.getGiaban()*sp.getSoluongban();
                        ln += (long) (sp.getGiaban()-sp.getGia())*sp.getSoluongban();
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(Thong_ke.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            DecimalFormat decimalFormat = new DecimalFormat("#,###");
            String format1 = decimalFormat.format(tsp);
            String format2 = decimalFormat.format(dt);
            String format3 = decimalFormat.format(ln);
            Tongsp.setText(format1);
            Tongtien.setText(format2);
            Lai.setText(format3);
            JOptionPane.showMessageDialog(rootPane, "Đã thống kê xong!");
        } 
        
        if (!txt_MaSp.getText().isEmpty() && cboLoaiSp.getSelectedItem().toString().equalsIgnoreCase("- Lựa Chọn -")) {
            int tsp=0;
            long dt=0;
            long ln=0;
            Date date1 = txt_Ngay1.getDate();
            Date date2 = txt_Ngay2.getDate();
            for (SanPham sp : daoSP.sanphamlist) {
                try {
                    DateFormat dateFormat = new SimpleDateFormat("E MMM dd HH:mm:ss zzz yyyy");
                    Date date = dateFormat.parse(sp.getNgayban());
                    if (date.compareTo(date1)>0 && date.compareTo(date2)<0 && sp.getMaSp().equalsIgnoreCase(txt_MaSp.getText().trim())) {
                        tsp += sp.getSoluongban();
                        dt += (long) sp.getGiaban()*sp.getSoluongban();
                        ln += (long) (sp.getGiaban()-sp.getGia())*sp.getSoluongban();
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(Thong_ke.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            DecimalFormat decimalFormat = new DecimalFormat("#,###");
            String format1 = decimalFormat.format(tsp);
            String format2 = decimalFormat.format(dt);
            String format3 = decimalFormat.format(ln);
            Tongsp.setText(format1);
            Tongtien.setText(format2);
            Lai.setText(format3);
            JOptionPane.showMessageDialog(rootPane, "Đã thống kê xong!");
        }
        
        if (txt_MaSp.getText().isEmpty() && !cboLoaiSp.getSelectedItem().toString().equalsIgnoreCase("- Lựa Chọn -")) {
            int tsp=0;
            long dt=0;
            long ln=0;
            Date date1 = txt_Ngay1.getDate();
            Date date2 = txt_Ngay2.getDate();
            for (SanPham sp : daoSP.sanphamlist) {
                try {
                    DateFormat dateFormat = new SimpleDateFormat("E MMM dd HH:mm:ss zzz yyyy");
                    Date date = dateFormat.parse(sp.getNgayban());
                    if (date.compareTo(date1)>0 && date.compareTo(date2)<0 && sp.getLoaisp().equalsIgnoreCase(cboLoaiSp.getSelectedItem().toString())) {
                        tsp += sp.getSoluongban();
                        dt += (long) sp.getGiaban()*sp.getSoluongban();
                        ln += (long) (sp.getGiaban()-sp.getGia())*sp.getSoluongban();
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(Thong_ke.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            DecimalFormat decimalFormat = new DecimalFormat("#,###");
            String format1 = decimalFormat.format(tsp);
            String format2 = decimalFormat.format(dt);
            String format3 = decimalFormat.format(ln);
            Tongsp.setText(format1);
            Tongtien.setText(format2);
            Lai.setText(format3);
            JOptionPane.showMessageDialog(rootPane, "Đã thống kê xong!");
        }
        
    }//GEN-LAST:event_ThongKeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lai;
    private javax.swing.JButton Lam_moi;
    private javax.swing.JButton ThongKe;
    private javax.swing.JTextField Tongsp;
    private javax.swing.JTextField Tongtien;
    private javax.swing.JButton btn_Thoat1;
    private javax.swing.JButton btn_quanly;
    private javax.swing.JButton btn_quaylai;
    private javax.swing.JComboBox<String> cboLoaiSp;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JTable tbl_spdaban;
    private javax.swing.JTextField txt_MaSp;
    private com.toedter.calendar.JDateChooser txt_Ngay1;
    private com.toedter.calendar.JDateChooser txt_Ngay2;
    // End of variables declaration//GEN-END:variables
}
